# Logistic Regression for MNIST Hand Written Digits

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import torch
import torchvision

In [5]:
trainingdata = torchvision.datasets.MNIST('./MNIST',train=True, transform=torchvision.transforms.ToTensor(), download=True)
testdata = torchvision.datasets.MNIST('./MNIST',train=False, transform=torchvision.transforms.ToTensor(), download=True)

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

In [ ]:
print(len(trainingdata), len(testdata))

In [ ]:
image, label = trainingdata[59999]
print(image.shape, label)

plt.imshow(image.squeeze().numpy())
plt.show()

In [ ]:
traindataloader = torch.utils.data.DataLoader(trainingdata, batch_size=64, shuffle=True)
testdataloader = torch.utils.data.DataLoader(testdata, batch_size=64, shuffle=False)

In [4]:
images, labels = iter(traindataloader).next()
print(images.size(), labels)

NameError: name 'traindataloader' is not defined

In [ ]:
class LR(torch.nn.Module):
    def __init__(self):
        super(LR, self).__init__()
        self.linear1 = torch.nn.Linear(28*28, 128) # W:784x128 , b:128x1 , parameters = [W,b]
        self.linear2 = torch.nn.Linear(128, 10)
    
    def forward(self, x):
        x = x.view(-1,28*28)
        transformed_x1 = self.linear1(x)
        transformed_x2 = self.linear2(transformed_x1)
        return transformed_x2
net = LR().cuda()
optimizer = torch.optim.SGD(net.parameters(), lr=0.01)
criterion = torch.nn.CrossEntropyLoss()

In [ ]:
train_loss_history = []
test_loss_history = []

for epoch in range(20):
    train_loss = 0.0
    test_loss = 0.0
    for i, data in enumerate(traindataloader):
        images, labels = data
        images = images.cuda()
        labels = labels.cuda()
        optimizer.zero_grad()
        predicted_output = net(images)
        loss = criterion(predicted_output, labels)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
    for i, data in enumerate(testdataloader):
        with torch.no_grad():
            images, labels = data
            images = images.cuda()
            labels = labels.cuda()
            predicted_output = net(images)
            loss = criterion(predicted_output, labels)
            test_loss += loss.item()
    train_loss = train_loss/len(traindataloader)
    test_loss = test_loss/len(testdataloader)
    train_loss_history.append(train_loss)
    test_loss_history.append(test_loss)
    print('Epoch %s finished with train loss %s and test loss %s'%(epoch, train_loss, test_loss))

Epoch 0 finished with train loss 1.0787747574767579 and test loss 0.5393653278517875
Epoch 1 finished with train loss 0.4735921543957328 and test loss 0.39646133358121677
Epoch 2 finished with train loss 0.3919314584974795 and test loss 0.35222991309158364
Epoch 3 finished with train loss 0.35903996639033114 and test loss 0.32994120043649033
Epoch 4 finished with train loss 0.3405328705223766 and test loss 0.3163745865273248
Epoch 5 finished with train loss 0.3284131602993779 and test loss 0.3075468081767392
Epoch 6 finished with train loss 0.31956984421242274 and test loss 0.3024480513587689
Epoch 7 finished with train loss 0.31256831040196836 and test loss 0.29671551495980303
Epoch 8 finished with train loss 0.3069480073842794 and test loss 0.29247235780830977
Epoch 9 finished with train loss 0.30237904564340484 and test loss 0.2899073371960289
Epoch 10 finished with train loss 0.2983993410603451 and test loss 0.28769470043005835
Epoch 11 finished with train loss 0.29518236690905814 

In [ ]:
predicted_output = net(images)
print(predicted_output[1])
print(torch.max(predicted_output, 1)[1])
loss = criterion(predicted_output, labels)
print(labels)
print(loss)

tensor([-4.8922, -3.3175,  7.2068,  3.3847, -3.6616, -0.4039, -4.3133,  1.4494,
         4.2532,  0.5469], device='cuda:0', grad_fn=<SelectBackward>)
tensor([1, 2, 8, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6], device='cuda:0')
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6], device='cuda:0')
tensor(0.1228, device='cuda:0', grad_fn=<NllLossBackward>)


In [6]:
from tqdm import tqdm

for i in tqdm(range(100)):
    pass



100%|██████████| 100/100 [00:00<00:00, 803506.51it/s]
